"""user language

Revision ID: 415d30a453b9
Revises: fca0ecff115d
Create Date: 2020-03-23 10:41:32.873952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415d30a453b9'
down_revision = 'fca0ecff115d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(length=5), nullable=True))
    op.create_index(op.f('ix_user_language'), 'user', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_language'), table_name='user')
    op.drop_column('user', 'language')
    # ### end Alembic commands ###
