"""gender

Revision ID: efe56d5ba3a3
Revises: b5c9ed2d6380
Create Date: 2020-03-22 19:30:32.689730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe56d5ba3a3'
down_revision = 'b5c9ed2d6380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
